version: '3.8'

services:
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_container
    restart: always
    environment:
      PMA_HOST: gateway01.ap-southeast-1.prod.aws.tidbcloud.com # Host of your live DB
      PMA_PORT: 4000 # Port of your live DB
      PMA_USER: Z4pBFxR54cTp1fj.root # Username of your live DB
      PMA_PASSWORD: Ut7ywrLxGMq623Is # Password of your live DB
      PMA_ABSOLUTE_URI: http://localhost:8080 # Ensure PHPMyAdmin resolves correctly
    ports:
      - "8080:80"
