services:
  - type: web
    name: phpmyadmin
    env: php
    region: oregon
    branch: main
    repo: https://github.com/MdShamsherAlam/phpMyAdmin # Your phpMyAdmin repo URL
    buildCommand: npm install # If you are using npm for builds (otherwise remove)
    startCommand: npm start # Or the correct command to start phpMyAdmin
    plan: free # Pricing plan
    autoDeploy: true # Automatically deploy when changes are pushed
    envVars: # Environment variables for phpMyAdmin
      - key: PMA_HOST
        value:https://phpmyadmin-vuz0.onrender.com # Host from your Render MySQL database 
      - key: PMA_USER
        value: your_db_username # Your Render MySQL username
      - key: PMA_PASSWORD
        value: your_db_password # Your Render MySQL password
      - key: PMA_PORT
        value: 3306 # Port for MySQL (default is 3306)


