services:
  - type: web # Specifies that this is a web service
    name: phpmyadmin # Name of the service
    env: node # Environment (node is for Node.js but we're using it for simplicity, as Render uses this environment variable setup)
    region: oregon # Choose your Render region (e.g., oregon, frankfurt)
    branch: main # The Git branch to deploy from
    repo: https://github.com/MdShamsherAlam/phpMyAdmin # Replace with your GitHub repository URL
    buildCommand: npm install # Build command (you may not need this if you're using Docker)
    startCommand: npm start # Command to start your app
    plan: free # Pricing plan (free, starter, or standard)
    autoDeploy: true # Deploy automatically when code is updated in the branch
    envVars: # Environment variables for phpMyAdmin
      - key: PMA_HOST
        value: db # Host name of the MySQL service, it should match the db service name in the docker-compose file
      - key: PMA_USER
        value: root # Database username (from your docker-compose)
      - key: PMA_PASSWORD
        value: rootpassword # Database password (from your docker-compose)
  - type: database # MySQL database service (managed by Render)
    name: university-db # Name of your database service
    plan: free # You can select the free or any other available database plan
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: rootpassword # The root password for the MySQL database
      - key: MYSQL_DATABASE
        value: university_hrms # The database name you set in your docker-compose
      - key: MYSQL_USER
        value: my_user # The MySQL username for phpMyAdmin
      - key: MYSQL_PASSWORD
        value: my_password # The password for the above username
    region: oregon # You can change to the region where you are deploying
