services:
  - type: web
    name: phpmyadmin
    env: docker
    branch: main # Replace with your branch name
    repo: https://github.com/MdShamsherAlam/phpMyAdmin # Replace with your repo URL
    buildCommand: "" # No build command needed for Dockerized apps
    startCommand: "" # No start command needed; Docker handles this
    plan: free # Render's free plan
    autoDeploy: true
    envVars:
      - key: PMA_HOST
        value: gateway01.ap-southeast-1.prod.aws.tidbcloud.com # Live DB host
      - key: PMA_PORT
        value: "4000" # Live DB port
      - key: PMA_USER
        value: Z4pBFxR54cTp1fj.root # Live DB username
      - key: PMA_PASSWORD
        value: Ut7ywrLxGMq623Is # Live DB password
